"""Central SEO thresholds and weights. Single source of truth for scoring + recommendations."""

# ---- Title ----
TITLE_IDEAL_MIN = 50
TITLE_IDEAL_MAX = 60
TITLE_ACCEPTABLE_MIN = 30
TITLE_ACCEPTABLE_MAX = 70
TITLE_SHORT_WARN = 30
TITLE_LONG_WARN = 70

# ---- Meta description ----
META_IDEAL_MIN = 120
META_IDEAL_MAX = 160
META_ACCEPTABLE_MIN = 80
META_ACCEPTABLE_MAX = 180
META_SHORT_WARN = 80
META_LONG_WARN = 180

# ---- URL ----
URL_MAX_GOOD = 75
URL_MAX_ACCEPTABLE = 100

# ---- Content ----
CONTENT_MIN_THIN = 150
CONTENT_MIN_GOOD = 300
CONTENT_IDEAL_MIN = 600
CONTENT_IDEAL_MAX = 1500
CONTENT_TOO_LONG = 2000

# ---- Keyword density (%) ----
DENSITY_IDEAL_MIN = 1.0
DENSITY_IDEAL_MAX = 2.5
DENSITY_OK_MIN = 0.5
DENSITY_OK_MAX = 3.0
DENSITY_WARN_MIN = 0.3
DENSITY_WARN_MAX = 4.0
DENSITY_STUFFING = 3.5

# ---- Weights (must sum to 1.0) ----
WEIGHT_TITLE = 0.25
WEIGHT_META = 0.20
WEIGHT_URL = 0.15
WEIGHT_CONTENT = 0.25
WEIGHT_KEYWORD = 0.15

# ---- Score points ----
SCORE_DENSITY_IDEAL = 100
SCORE_DENSITY_OK = 70
SCORE_DENSITY_WARN = 40
SCORE_DENSITY_LOW = 20
