# Generated by Django 5.2.17 on 2026-09-03 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Page URL or slug (e.g. /blog/seo-tips)', max_length=500)),
                ('title', models.CharField(help_text='Page title tag', max_length=200)),
                ('meta_description', models.CharField(help_text='Meta description tag', max_length=500)),
                ('content', models.TextField(help_text='Main page content / body text')),
                ('target_keyword', models.CharField(help_text='Primary keyword to optimize for', max_length=100)),
                ('title_score', models.PositiveSmallIntegerField(default=0)),
                ('meta_score', models.PositiveSmallIntegerField(default=0)),
                ('url_score', models.PositiveSmallIntegerField(default=0)),
                ('keyword_density', models.FloatField(default=0.0, help_text='Density in %')),
                ('content_score', models.PositiveSmallIntegerField(default=0)),
                ('overall_score', models.PositiveSmallIntegerField(default=0)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Owner of the report. Null for anonymous audits.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SEO Report',
                'verbose_name_plural': 'SEO Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
