# Generated by Django 5.2.17 on 2026-09-03 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='seoreport',
            name='overall_score',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='seoreport',
            name='target_keyword',
            field=models.CharField(db_index=True, help_text='Primary keyword to optimize for', max_length=100),
        ),
        migrations.AddIndex(
            model_name='seoreport',
            index=models.Index(fields=['user', '-created_at'], name='calculator__user_id_95edb9_idx'),
        ),
        migrations.AddIndex(
            model_name='seoreport',
            index=models.Index(fields=['overall_score'], name='calculator__overall_13587a_idx'),
        ),
    ]
