# Generated by Django 5.2.17 on 2026-09-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_seoreport_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoreport',
            name='title',
            field=models.CharField(db_index=True, help_text='Page title tag', max_length=200),
        ),
    ]
